app:
  name: SWIFT
server:
  port: 8081
  servlet:
    context-path: /swift

spring:
  profiles:
    active: @app.env@

crypto:
  aes:
    size: @crypto.aes.size@
  rsa:
    size: @crypto.rsa.size@

swift:
  mybatis:
    mapper-locations:
      master: classpath*:sqlmapper/*.xml
