server:
  port: 8081
  servlet:
    context-path: /swift
spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://24.233.1.242:3306/swift?characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(P6ouDpTphpE+PSHGnAYdFAh+7E7iZc6sOhaow3kxz9D89JvutQ==)
        password: ENC(QMoZDwCZHN7zfVmqfGYzdtILnhcQQ23pnZ+WRGOHcHolowuAspMbl4nWpQs=)
        validation-query: SELECT 1 from dual
        filters: stat,wall,slf4j
  data:
    redis:
      host: 24.233.1.242
      port: 6379
      password: ENC(DEwfQjMb123KgJaifffE4rDS/66ELvoWVM/bHuR0XSAhSpkSTkUA6A==)
      database: 0
logging:
  level:
    root: info
security:
  auth:
    login-path: /auth/login
    white-list: /auth/**, /swagger-ui/**, /v3/api-docs/**
crypto:
  aes:
    key: Td/c5P7o1Hqp1IbQwaDw1O2DasSjkeBQSeTz4eQm96Lt0R6dEEhfJiqxpdfIrJcBLG02CkO3ELLCDTp7Chqzdx/JR0XejYgsf+7XczM4nUY2FnnqP5mdiR32+73O7sZg7RKFRDISlrHj7ptq+cnqgW2D+yQIyx9CAf2SKER424+qXgJKow6UzlaGT5UWr1I4pjCOKv1RqlfyFgTp2UKZvBAX4T4ZSoxWAL8uH91xnVtVhJsb9PnGDRdzU/nKNaVTHyyfodxxhZNI3I1osoCFzCVjWUXv3jgT9k1+NDZ+3wfPRTAK7jV6wqWS9ws7He/ZEFWlC14hRiTI+mSNfJNoVA==
  rsa:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkZLxJwVoj0SSQt32J4MpSXet3JUiq+qDkEXjdJvLfG4DieYJowKrnnkUXTdqVwptPoArBrWdoJUVBwsUxUrycTDGdf6WYt1/KY6g+UuuzuuHOdftSTi+YV42ZMww4Xs7lo66jYODlkgYwkK4V/p/10QrFzyi/nIOW5QPaTeKpmdGv2m+Jh8xJuOhLMVDmYAkakdf7cOpb6p31LfmB9Nrra+F1gNG93BAvdoi+Hj+VCuQ3eLToJzclnmHPZhZckwKoWfhgTZfJyKrLrxB6/CZr56d8440evVEgWmMYjKn+X/8ukZ6PP0Yh6j5kEC4R933PyMjS2dOPtRIaD1l1QAKEwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRkvEnBWiPRJJC3fYngylJd63clSKr6oOQReN0m8t8bgOJ5gmjAqueeRRdN2pXCm0+gCsGtZ2glRUHCxTFSvJxMMZ1/pZi3X8pjqD5S67O64c51+1JOL5hXjZkzDDhezuWjrqNg4OWSBjCQrhX+n/XRCsXPKL+cg5blA9pN4qmZ0a/ab4mHzEm46EsxUOZgCRqR1/tw6lvqnfUt+YH02utr4XWA0b3cEC92iL4eP5UK5Dd4tOgnNyWeYc9mFlyTAqhZ+GBNl8nIqsuvEHr8Jmvnp3zjjR69USBaYxiMqf5f/y6Rno8/RiHqPmQQLhH3fc/IyNLZ04+1EhoPWXVAAoTAgMBAAECggEAHII05OnrvKb2p861Lq7Cjqc37stsE1PleQMe1M7P7mnTGpXozDoxJuNaaBj6o9ogY82Q34sAuBqKGCuE4VBYo28kZqY5iFoNVbOfdcLrFI3OmTbeuui4a/QZ3eqZJgdOt6DzCtS3F969romHdX9SuvMYJ0BSQVdP1YJs9DOS3Rxv7ryBHKqbkAHE6e54K822ROCFR1XEL6attmpEra5MrUIImHhWi9EGXtIaBFDgY4r0rhvC6cAhFwxdtcTxVavZUubFVeireWUeEyqZefsO2eFFtBDr8idyYdneIpTcQ9HaayR6snvH/IACotFquQWxGdlxHjANvMQtGjuae/S2qQKBgQDKJyfEPtlz1HYY9rMVeHyo71QWpZty4lEKOI5D0sFLVXJJJbvOurTx1L6E+64I4pUZj73kHy+ShMm/WIZ7NI4C/cICMvPv7DfPxDiBZIF7Hpq+W9xSL0WEW8+aaWySFXue9mhd5GrpOEHSoauCAgKTwW19hc96uHzP+g9YE2ePWwKBgQC4Wahfi8jcjjXIrvUgXt6FQI1MS++dfw+ACdjt5PJ8BsO8yxF8H6ia2+Tgv8oTuUSFvrtjvfaAsDXTCsPgUsMQ/THXHTtGsCjZwT9VZ/poR25VtRpkXRJiTcm8ljCIG/bCGEMfJi/wsX0XGRtwfLiHtm0Dk5CB6xeD838XShLlqQKBgHSClLzarGHB9j71EMozI0YKiiBzWmCgZ6zIY9ZbReSxXqkiAlhn65nlz9i9ZdThIqYU3pD4GGcN+Wk7EGc6Jw86SfMSgt2o+5HXuel5j9byEKXeM+F6NUrPz5tjX5vindlEk2pqF+RK9ET9wOexWOLn/L73vFkys1z69pUAuhM5AoGALHa7jKgLf17xjADe8LrREvS53+Ak4CjoVSqK3v4smkuLZHraMcT1Brzo3GiF1fIGm/ef/POxg+J8aPWcvvtXPz7Cia7sQCV3BOZ+XxwgIoywCQ4QWoq0R2+Zq9nRxNJx1ujBL78nKve0QyD0JFKAs4MFkipCXYOVfWb6jWR5YFkCgYEAinS9dQSx28jx9YodMXAZSrLxLqdDoNT2GBThbc2qY7Ji4PSfHsYdyR8ogCdufnXB0IZM543zjQmqqZ3nHvT2F026S/lvIS7wts/fRpKcSkj0zsT76uUyNVixTmblP2PR5HErxMJ4MjQo/jIPxWQRHaDDwMGfTIvkDRuj17wUOdQ=
